server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081

logging:
  level: INFO
  loggers:
    com.example.helloworld.jmx: DEBUG

template: "Hello, %s! This is conversation #%d"
defaultName: Stranger
initialConversationCount: 0
